---
# Automatización de tareas programadas en Windows

- name: Crear tarea programada de backup diaria
  win_scheduled_task:
    name: "Backup diario"
    description: "Backup de datos cada día a las 2am"
    actions:
      - path: Powershell.exe
        arguments: "-File C:\Scripts\backup.ps1"
    trigger:
      - type: daily
        start_boundary: '2025-01-01T02:00:00'
    username: SYSTEM
    state: present

- name: Crear tarea programada de limpieza semanal
  win_scheduled_task:
    name: "Limpieza semanal"
    description: "Limpieza de temporales cada domingo a las 3am"
    actions:
      - path: Powershell.exe
        arguments: "-File C:\Scripts\cleanup.ps1"
    trigger:
      - type: weekly
        days_of_week: Sunday
        start_boundary: '2025-01-05T03:00:00'
    username: SYSTEM
    state: present
