---
# Tareas para servicios críticos

- name: Habilitar y arrancar servicio de hora (w32time)
  ansible.windows.win_service:
    name: w32time
    start_mode: auto
    state: started

- name: Habilitar y arrancar WinRM
  ansible.windows.win_service:
    name: WinRM
    start_mode: auto
    state: started

- name: Comprobar estado de procesos críticos
  ansible.windows.win_shell: 'Get-Process | Where-Object {$_.Name -eq "svchost"}'
  register: process_status

- name: Debug - Mostrar contenido de process_status
  ansible.builtin.debug:
    var: process_status

- name: Crear directorio de reportes si no existe
  ansible.windows.win_file:
    path: "C:\\AnsibleReports\\{{ inventory_hostname }}"
    state: directory

- name: Guardar salida de procesos críticos
  ansible.windows.win_copy:
    content: "{{ process_status.stdout | default('No stdout available') }}"
    dest: "C:\\AnsibleReports\\{{ inventory_hostname }}\\process_status.txt"
