---
# Tareas de almacenamiento

- name: Obtener información de discos y volúmenes
  community.windows.win_disk_facts:
  register: disk_info

- name: Mostrar información de discos
  debug:
    var: disk_info

- name: Formatear disco nuevo y crear volumen (¡PRUEBA SOLO EN ENTORNOS DE TEST!)
  community.windows.win_partition:
    disk_number: 1
    partition_number: 1
    drive_letter: D
    state: present
  when: disk_info.ansible_facts.ansible_disks | length > 1
  # ¡ADVERTENCIA! Esta tarea borra datos. Usar solo en pruebas.

- name: Crear carpeta C:\data
  ansible.windows.win_file:
    path: 'C:\data'
    state: directory

- name: Asignar permisos NTFS a C:\data
  ansible.windows.win_acl:
    path: 'C:\data'
    user: '{{ win_admin_user }}'
    rights: FullControl
    type: allow
