---
# Dispatcher principal para base

- name: Incluir tareas de Linux
  include_tasks: linux/main.yml
  when: ansible_facts['os_family'] in ['Debian', 'RedHat']

- name: Incluir tareas de Windows
  include_tasks: windows/main.yml
  when: ansible_facts['os_family'] == 'Windows'

- name: Incluir optimización gaming (solo Zentyal)
  include_role:
    name: gaming
  when: gaming_enabled | default(false)

- name: Incluir políticas académicas (solo Windows Server)
  include_tasks: windows/academic_policies.yml
  when: academic_mode | default(false) and ansible_facts['os_family'] == 'Windows'