---
# Tareas base para preparar Windows Server 2022

- name: Instalar actualizaciones críticas de Windows
  ansible.windows.win_updates:
    category_names: ['CriticalUpdates']
    state: installed
  register: update_result

- name: Instalar el rol IIS (Web-Server) si se requiere
  ansible.windows.win_feature:
    name: Web-Server
    state: present
  register: iis_result

- name: Crear carpeta C:\Scripts
  ansible.windows.win_file:
    path: '{{ default_scripts_path }}'
    state: directory

- name: Asignar permisos a C:\Scripts
  ansible.windows.win_acl:
    path: '{{ default_scripts_path }}'
    user: '{{ win_admin_user }}'
    rights: FullControl
    type: allow

- name: Copiar utilidades y scripts a C:\Scripts
  ansible.windows.win_copy:
    src: "files/windows/{{ item }}"
    dest: '{{ default_scripts_path }}\{{ item }}'
  with_items:
    - backup.ps1
    - cleanup.ps1

- name: Configurar zona horaria
  community.windows.win_timezone:
    timezone: "SA Pacific Standard Time"  # Perú, Colombia, Ecuador (UTC-5)

- name: Cambiar nombre de host si es necesario
  ansible.windows.win_hostname:
    name: "{{ inventory_hostname }}"
  when: inventory_hostname is defined

# BASE WINDOWS: Seguridad, acceso, hora, firewall, antivirus

- name: Aplicar controles de acceso y contraseñas seguras
  import_tasks: access_controls.yml

- name: Configurar firewall y antivirus
  import_tasks: firewall_antivirus.yml

- name: Configurar zona horaria
  import_tasks: timezone.yml

- name: Configurar reglas de firewall académicas
  import_tasks: firewall_academic_rules.yml
  when: academic_mode | default(false)